* Prompt
The following is a quotation from a pali text, and two reliable, phenomenologically-informed translation(s). Please use the available text to triangulate an excellent German rendition, true to the original and with echoes of the interpretations found in the provided English translation(s). If established buddhist terms in german do not match the vibe or meanings of the translations, opt for more fitting terms.

* Chapter 1
** MN 107
*** Dojč/Döïtshke
#+begin_quote
„Ebenso, o Brahmane, wenn der Tathāgata einen Menschen, der zu zähmen ist, in seine Obhut bekommt, unterweist er ihn zuallererst folgendermaßen: ‚Komm, Mönch, sei sittenrein. Lebe, eingeschränkt durch die Ordensregeln, vollkommen im Verhalten und im rechten Wandel, siehst du die Gefahr schon im geringsten Vergehen. Indem du sie übernommen hast, übe dich in den Übungsregeln.‘

Wenn der Mönch, o Brahmane, sittenrein ist, [...] sieht er die Gefahr schon im geringsten Vergehen, dann unterweist ihn der Tathāgata weiter: ‚Komm, Mönch, sei einer, der die Tore der Sinne bewacht. Wenn du mit dem Auge eine Form erblickst, sei einer, der nicht am Anzeichen haftet, nicht am Detail. Denn wenn du unbezähmt mit dem Auge lebst, könnten üble, unheilsame Geisteszustände, Begierde und Widerwille, in dich einströmen. Daher übe dich in deren Bezähmung; bewache das Auge, erlange die Bezähmung des Auges. Wenn du mit dem Ohr einen Ton hörst [...] Wenn du mit der Nase einen Duft riechst [...] Wenn du mit der Zunge einen Geschmack schmeckst [...] Wenn du mit dem Körper eine Berührung fühlst [...] Wenn du mit dem Geist ein Geistesobjekt wahrnimmst, sei einer, der nicht am Anzeichen haftet, nicht am Detail. Denn wenn du unbezähmt mit dem Geist lebst, könnten üble, unheilsame Geisteszustände, Begierde und Widerwille, in dich einströmen. Daher übe dich in deren Bezähmung; bewache den Geist, erlange die Bezähmung des Geistes.‘

Wenn der Mönch, o Brahmane, einer ist, der die Tore der Sinne bewacht, dann unterweist ihn der Tathāgata weiter: ‚Komm, Mönch, sei maßvoll beim Essen. Indem du weise reflektierst, nimmst du Speise zu dir: nicht zum Vergnügen, nicht zum Rausch, nicht zur Zierde, nicht zur Verschönerung, sondern einzig um diesen Körper am Leben zu erhalten, um Schaden zu beenden, um das heilige Leben zu unterstützen, indem du denkst: So werde ich altes Gefühl beenden und kein neues Gefühl aufsteigen lassen, und ich werde ein untadeliges Leben führen und mich wohl fühlen.‘

Wenn der Mönch, o Brahmane, maßvoll beim Essen ist, dann unterweist ihn der Tathāgata weiter: ‚Komm, Mönch, sei einer, der sich der Wachsamkeit widmet. Am Tage, beim Gehen und Sitzen, läutere deinen Geist von hemmenden Zuständen. In der ersten Nachtwache, beim Gehen und Sitzen, läutere deinen Geist von hemmenden Zuständen. In der mittleren Nachtwache, bereite dir auf der rechten Seite das Löwenlager, einen Fuß über dem anderen, achtsam und wissensklar, die Vorstellung des Aufstehens im Geiste haltend. In der letzten Nachtwache, erhebe dich und läutere beim Gehen und Sitzen deinen Geist von hemmenden Zuständen.‘

Wenn der Mönch, o Brahmane, einer ist, der sich der Wachsamkeit widmet, dann unterweist ihn der Tathāgata weiter: ‚Komm, Mönch, sei einer, der mit Achtsamkeit und Wissensklarheit ausgestattet ist. Handle wissensklar beim Hingehen und Zurückkehren; beim Hinblicken und Wegblicken; beim Beugen und Strecken der Glieder; beim Tragen der Ober- und Unterrobe, der Almosenschale; beim Essen, Trinken, Kauen und Schmecken; beim Verrichten der Notdurft; beim Gehen, Stehen, Sitzen, Einschlafen, Aufwachen, Reden und Schweigen.‘

Wenn der Mönch, o Brahmane, einer ist, der mit Achtsamkeit und Wissensklarheit ausgestattet ist, dann unterweist ihn der Tathāgata weiter: ‚Komm, Mönch, suche eine abgeschiedene Lagerstätte auf: einen Wald, den Fuß eines Baumes, einen Berg, eine Schlucht, eine Berghöhle, einen Leichenacker, ein Walddickicht, eine freie Fläche, einen Strohhaufen.‘

Er sucht eine abgeschiedene Lagerstätte auf: einen Wald, den Fuß eines Baumes, einen Berg, eine Schlucht, eine Berghöhle, einen Leichenacker, ein Walddickicht, eine freie Fläche, einen Strohhaufen. Nach dem Almosengang, nach der Mahlzeit, setzt er sich mit gekreuzten Beinen nieder, den Oberkörper aufgerichtet, und richtet die Achtsamkeit nach vorn, auf den Gegenwartspunkt.

Nachdem er Begierde gegenüber der Welt aufgegeben hat, verweilt er mit einem von Begierde freien Geist; er läutert seinen Geist von Begierde. Nachdem er Übelwollen und Hass aufgegeben hat, verweilt er mit einem von Übelwollen freien Geist, voll Mitgefühl für das Wohlergehen aller lebenden Wesen; er läutert seinen Geist von Übelwollen und Hass. Nachdem er Trägheit und Mattheit aufgegeben hat, verweilt er frei von Trägheit und Mattheit, voll Wahrnehmung von Licht, achtsam und wissensklar; er läutert seinen Geist von Trägheit und Mattheit. Nachdem er Rastlosigkeit und Gewissensunruhe aufgegeben hat, verweilt er unaufgeregt, mit einem innerlich beruhigten Geist; er läutert seinen Geist von Rastlosigkeit und Gewissensunruhe. Nachdem er den Zweifel aufgegeben hat, verweilt er dem Zweifel entronnen, ohne Ungewissheit heilsamen Geisteszuständen gegenüber; er läutert seinen Geist von Zweifel.

Nachdem er diese fünf Hemmnisse aufgegeben hat, diese Befleckungen des Geistes, die die Weisheit schwächen, dann, ganz abgeschieden von Sinnesreizen, abgeschieden von unheilsamen Geisteszuständen, tritt er in die erste Vertiefung ein, die mit Denken und Überlegen geboren wird, mit Verzückung und Glücksgefühl, die aus der Abgeschiedenheit entstanden ist, und verweilt in ihr. Mit der Stillung von Denken und Überlegen tritt er in die zweite Vertiefung ein, die innere Beruhigung und Einheit des Gemüts ohne Denken und Überlegen, mit Verzückung und Glücksgefühl, die aus der Sammlung entstanden sind, und verweilt in ihr. Nach dem Verblassen der Verzückung, in Gleichmut verweilend, achtsam und wissensklar, voll körperlich empfundenen Glücks, tritt er in die dritte Vertiefung ein, von der die Edlen sagen: ‚Glückselig verweilt derjenige, der voll Gleichmut und Achtsamkeit ist‘, und verweilt in ihr. Nach dem Überwinden von Glück und Schmerz und dem schon früheren Schwinden von Frohsinn und Trauer, tritt er in die vierte Vertiefung ein, die aufgrund von Gleichmut und Achtsamkeit Läuterung ist, weder Schmerz noch Glück, und verweilt in ihr.

Jenen Mönchen, o Brahmane, die Lehrlinge sind, die das Ziel noch nicht erreicht haben und unermüdlich im Streben nach dem höchsten Heil von der Fessel verweilen, gilt diese meine Unterweisung. Doch jenen Mönchen, die Arahants sind, deren Triebe vernichtet sind, die das heilige Leben gelebt, getan was getan werden musste, die Bürde abgelegt, das wahre Ziel erreicht haben, deren Daseinsfesseln völlig zerstört und die durch vollkommene Erkenntnis befreit sind, – diese Dinge führen bei ihnen zu einem gegenwärtig glücklichen Verweilen und zu Achtsamkeit und Wissensklarheit.“
#+end_quote
*** Pāli
#+begin_quote
evameva kho, brāhmaṇa, tathāgato purisadammaṃ labhitvā paṭhamaṃ evaṃ vineti — ‘ehi tvaṃ, bhikkhu, sīlavā hohi, pātimokkhasaṃvarasaṃvuto viharāhi ācāragocarasampanno aṇumattesu vajjesu bhayadassāvī, samādāya sikkhassu sikkhāpadesū’”ti.

♦ “yato kho, brāhmaṇa, bhikkhu sīlavā hoti, pātimokkhasaṃvarasaṃvuto viharati ācāragocarasampanno aṇumattesu vajjesu bhayadassāvī, samādāya sikkhati sikkhāpadesu, tamenaṃ tathāgato uttariṃ vineti — ‘ehi tvaṃ, bhikkhu, indriyesu guttadvāro hohi, cakkhunā rūpaṃ disvā mā nimittaggāhī hohi mānubyañjanaggāhī. yatvādhikaraṇamenaṃ cakkhundriyaṃ asaṃvutaṃ viharantaṃ abhijjhādomanassā pāpakā akusalā dhammā anvāssaveyyuṃ tassa saṃvarāya paṭipajjāhi; rakkhāhi cakkhundriyaṃ, cakkhundriye saṃvaraṃ āpajjāhi. sotena saddaṃ sutvā ... pe ... ghānena gandhaṃ ghāyitvā ... pe ... jivhāya rasaṃ sāyitvā ... pe ... kāyena phoṭṭhabbaṃ phusitvā ... pe ... manasā dhammaṃ viññāya mā nimittaggāhī hohi mānubyañjanaggāhī. yatvādhikaraṇamenaṃ manindriyaṃ asaṃvutaṃ viharantaṃ abhijjhādomanassā pāpakā akusalā dhammā anvāssaveyyuṃ tassa saṃvarāya paṭipajjāhi; rakkhāhi manindriyaṃ, manindriye saṃvaraṃ āpajjāhī’”ti.

♦ “yato kho, brāhmaṇa, bhikkhu indriyesu guttadvāro hoti, tamenaṃ tathāgato uttariṃ vineti — ‘ehi tvaṃ, bhikkhu, bhojane mattaññū hohi. paṭisaṅkhā yoniso āhāraṃ āhāreyyāsi — neva davāya na madāya na maṇḍanāya na vibhūsanāya, yāvadeva imassa kāyassa ṭhitiyā yāpanāya vihiṃsūparatiyā brahmacariyānuggahāya — iti purāṇañca vedanaṃ paṭihaṅkhāmi, navañca vedanaṃ na uppādessāmi, yātrā ca me bhavissati anavajjatā ca phāsuvihāro cā’”ti.

♦ “yato kho, brāhmaṇa, bhikkhu bhojane mattaññū hoti, tamenaṃ tathāgato uttariṃ vineti — ‘ehi tvaṃ, bhikkhu, jāgariyaṃ anuyutto viharāhi, divasaṃ caṅkamena nisajjāya āvaraṇīyehi dhammehi cittaṃ parisodhehi, rattiyā paṭhamaṃ yāmaṃ caṅkamena nisajjāya āvaraṇīyehi dhammehi cittaṃ parisodhehi, rattiyā majjhimaṃ yāmaṃ dakkhiṇena passena sīhaseyyaṃ kappeyyāsi pāde pādaṃ accādhāya sato sampajāno uṭṭhānasaññaṃ manasikaritvā, rattiyā pacchimaṃ yāmaṃ paccuṭṭhāya caṅkamena nisajjāya āvaraṇīyehi dhammehi cittaṃ parisodhehī’”ti.

♦ “yato kho, brāhmaṇa, bhikkhu jāgariyaṃ anuyutto hoti, tamenaṃ tathāgato uttariṃ vineti — ‘ehi tvaṃ, bhikkhu, satisampajaññena samannāgato hohi, abhikkante paṭikkante sampajānakārī, ālokite vilokite sampajānakārī, samiñjite pasārite sampajānakārī, saṅghāṭipattacīvaradhāraṇe sampajānakārī, asite pīte khāyite sāyite sampajānakārī, uccārapassāvakamme sampajānakārī, gate ṭhite nisinne sutte jāgarite bhāsite tuṇhībhāve sampajānakārī’”ti.

♦ “yato kho, brāhmaṇa, bhikkhu satisampajaññena samannāgato hoti, tamenaṃ tathāgato uttariṃ vineti — ‘ehi tvaṃ, bhikkhu, vivittaṃ senāsanaṃ bhajāhi araññaṃ rukkhamūlaṃ pabbataṃ kandaraṃ giriguhaṃ susānaṃ vanapatthaṃ abbhokāsaṃ palālapuñjan’ti. so vivittaṃ senāsanaṃ bhajati araññaṃ rukkhamūlaṃ pabbataṃ kandaraṃ giriguhaṃ susānaṃ vanappatthaṃ abbhokāsaṃ palālapuñjaṃ. so pacchābhattaṃ piṇḍapātapaṭikkanto nisīdati pallaṅkaṃ ābhujitvā, ujuṃ kāyaṃ paṇidhāya, parimukhaṃ satiṃ upaṭṭhapetvā. so abhijjhaṃ loke pahāya vigatābhijjhena cetasā viharati, abhijjhāya cittaṃ parisodheti; byāpādapadosaṃ pahāya abyāpannacitto viharati sabbapāṇabhūtahitānukampī, byāpādapadosā cittaṃ parisodheti; thinamiddhaṃ {thīnamiddhaṃ (sī. syā. kaṃ. pī.)} pahāya vigatathinamiddho viharati ālokasaññī sato sampajāno, thinamiddhā cittaṃ parisodheti; uddhaccakukkuccaṃ pahāya anuddhato viharati ajjhattaṃ vūpasantacitto, uddhaccakukkuccā cittaṃ parisodheti; vicikicchaṃ pahāya tiṇṇavicikiccho viharati akathaṃkathī kusalesu dhammesu, vicikicchāya cittaṃ parisodheti.

♦ 76. “so ime pañca nīvaraṇe pahāya cetaso upakkilese paññāya dubbalīkaraṇe vivicceva kāmehi vivicca akusalehi dhammehi savitakkaṃ savicāraṃ vivekajaṃ pītisukhaṃ paṭhamaṃ jhānaṃ upasampajja viharati. vitakkavicārānaṃ vūpasamā ajjhattaṃ sampasādanaṃ ... pe ... dutiyaṃ jhānaṃ upasampajja viharati. pītiyā ca virāgā... tatiyaṃ jhānaṃ upasampajja viharati. sukhassa ca pahānā... catutthaṃ jhānaṃ upasampajja viharati.

♦ “ye kho te, brāhmaṇa, bhikkhū sekkhā {sekhā (sabbattha)} apattamānasā anuttaraṃ yogakkhemaṃ patthayamānā viharanti tesu me ayaṃ evarūpī anusāsanī hoti. ye pana te bhikkhū arahanto khīṇāsavā vusitavanto katakaraṇīyā ohitabhārā anuppattasadatthā parikkhīṇabhavasaṃyojanā sammadaññā vimuttā tesaṃ ime dhammā diṭṭhadhammasukhavihārāya ceva saṃvattanti, satisampajaññāya cā”ti.
#+end_quote

*** OWTJ
#+begin_quote
… When the Tathāgata gets a person fit to be tamed, he first trains him
like this:
‘(1) Come, monk. Be virtuous. Live restrained in accordance with
the Pāṭimokkha, accomplished in your behavior and sphere of activity.
Train yourself, having undertaken the training rules, seeing danger in
the slightest faults.’
When the monk is virtuous … seeing danger in the slightest faults,
the Tathāgata then trains him further:
‘(2) Come, monk. Be one who is guarded in the doors of your sense
faculties. On seeing a form with the eye, don’t grasp at any signs and
features (significance) by which—if you were to live without restraint
over the faculty of the eye—unskilful qualities such as greed or distress
might assail you. Practice restraint. Protect the faculty of the eye.
Attain restraint concerning the faculty of the eye. On hearing a sound
with the ear … On smelling an aroma with the nose … On tasting a
flavour with the tongue … On touching a tactile sensation with the
body … On cognising an idea with the intellect, don’t grasp at any signs
and features by which—if you were to live without restraint over the
faculty of the intellect—unskilful qualities such as greed or distress
might assail you. Practice restraint. Protect the faculty of the intellect.
Attain restraint concerning the faculty of the intellect.’
When the monk is one who is guarded in the doors of his sense
faculties … the Tathāgata then trains him further:
‘(3) Come, monk. Be one who moderates his eating. Concurrently
reflecting, take your food not playfully, nor for intoxication, nor for
putting on weight, nor for beautification, but simply for the survival and
continuance of this body, for ending its afflictions, for the support of the
holy life, thinking, “I will destroy old feelings and not create new feelings.
Therefore I will maintain myself, be blameless and live at ease.’
When the monk is one who moderates his eating … the Tathāgata
then trains him further:

‘(4) Come, monk. Be one who is devoted to wakefulness. During
the day, sitting and walking back and forth, cleanse your mind of
obstructive things. During the first watch of the night, sitting and
walking back and forth, cleanse your mind of obstructive things.
During the second watch of the night, reclining on your right side,
take up the lion’s posture, one foot placed on top of the other,
recollected, alert, with your mind set on getting up. During the last
watch of the night, sitting and walking back and forth, cleanse your
mind of obstructive things.’
When the monk is one who is devoted to wakefulness … the
Tathāgata then trains him further:
‘(5) Come, monk. Be one who is possessed of recollection and
awareness. When going forward and returning, make yourself
aware. When looking toward and looking away … When bending and
extending your limbs … When carrying your outer cloak, upper robe,
and bowl … When eating, drinking, chewing, and tasting … When
urinating and defecating … When walking, standing, sitting, falling
asleep, waking up, talking, and remaining silent, make yourself aware.’
When the monk is one who is possessed of recollection and
awareness … The Tathāgata then trains him further:
‘(6) Come, monk. Seek out a secluded dwelling: a wilderness, the
shade of a tree, a mountain, a glen, a hillside cave, a charnel ground, a
forest grove, the open air, a heap of straw.’
He seeks out a secluded residence: a wilderness, the shade of a tree,
a mountain, a glen, a hillside cave, a charnel ground, a forest grove,
the open air, a heap of straw. After his meal, returning from his alms
round, he sits down, crosses his legs, holds his body upright, and
brings recollection to the fore.
(7) Abandoning lust with regard to the world, he lives with an
awareness devoid of lust. He cleanses his mind of lust. Abandoning
ill will and anger, he lives with an awareness devoid of ill will,
compassionate to the welfare of all living beings. He cleanses his mind
of ill will and anger. Abandoning indolence and tiredness, he lives
with an awareness devoid of indolence and tiredness, recollected,
alert, percipient of light. He cleanses his mind of indolence and
tiredness. Abandoning restlessness and anxiety, he lives undisturbed,
his mind inwardly stilled. He cleanses his mind of restlessness and
anxiety. Abandoning doubt, he lives having crossed over doubt, with
no perplexity with regard to skilful qualities. He cleanses his mind of
doubt.
(8) having abandoned these five hindrances—imperfections of
mind that weaken discernment—then, withdrawn from sensual
desire, withdrawn from unskilful qualities, he enters and remains
in the first comprehension: joy and pleasure born of withdrawal,
with thinking and pondering … the second comprehension, the third
comprehension, the fourth comprehension: purity of equanimity and
recollection, neither pleasure nor pain.
This is my instruction to those monks in training who have not
attained the goal, but remain intent on the unsurpassed safety from
bondage. But for those monks who are arahants—whose defilements
are ended, who have reached fulfillment
–
done the task, laid down
the burden, attained the true goal, laid to waste the impediment of
being, and who are released through right understanding—these
qualities lead both to a pleasant abiding in the here and now, and to
recollection and awareness.
#+end_quote
*** Anigha
#+begin_quote
when the Realized One obtains a man for training, he first guides him like this: ‘Come, bhikkhu, live fulfilling virtue and the training rules. Live restrained by the code of conduct, endowed with proper behavior and a suitable environment. Seeing danger in the slightest fault, train in the training rules.’ [2]

When the bhikkhu is virtuous, the Realized One guides him further: ‘Come, bhikkhu, guard your sense doors. When you see a sight with the eyes, do not grasp at signs and features of it [3] on account of which—due to abiding with the eye faculty unrestrained—bad, unbeneficial thoughts of longing and upset would flow in on you. Practice to restrain that; guard the eye faculty and bring about the restraint of the eye faculty.’ When you hear a sound with the ear … When you smell an odor with the nose … When you taste a flavor with the tongue … When you touch a touch with the body … When you cognize a phenomenon with the mind, do not grasp at signs and features of it on account of which—due to abiding with the mental faculty unrestrained—bad, unbeneficial thoughts of longing and upset would flow in on you. Practice to restrain that; guard the mental faculty and bring about the restraint of the mental faculty.

When the bhikkhu has his sense doors guarded, the Realized One guides him further: ‘Come, bhikkhu, be moderate in eating. [4] Eat with reflection in light of the origin: ‘Not for entertainment, indulgence, beautification, or adornment, but only to sustain this body, to avoid harm, and to support the renunciate life. In this way, I shall put an end to old discomfort and not give rise to new discomfort, and I shall live blamelessly and at ease.’

When the bhikkhu eats in moderation, the Realized One guides him further: ‘Come, bhikkhu, be committed to vigilance. During the day, cleanse your mind of obstructive states while walking or sitting. During the first watch of the night, cleanse your mind of obstructive states while walking or sitting. During the second watch of the night, you should lie down in the lion’s posture—on the right side, placing one foot on top of the other—recollected and aware, having set the intention to arise. Having arisen in the last watch of the night, continue to cleanse your mind of obstructive states while walking or sitting.’ [5]

When the bhikkhu is committed to vigilance, the Realized One guides him further: ‘Come, bhikkhu, be possessed of remembrance-and-awareness. Act with awareness when going out and returning; when looking ahead and aside; when bending and extending the limbs; when bearing the outer robe, bowl, and robes; when eating, drinking, chewing, and tasting; when urinating and defecating; when walking, standing, sitting, sleeping, waking, speaking, and keeping silent.’ [6]

When the bhikkhu is possessed of remembrance-and-awareness, the Realized One guides him further: ‘Come, bhikkhu, frequent a secluded lodging—a wilderness, the root of a tree, a hill, a ravine, a mountain cave, a charnel ground, a forest, the open air, a heap of straw.’ And he does so.

After the meal, he returns from almsround, sits down cross-legged, sets his body straight, and establishes remembrance at the fore. With the giving up of longing with regard to the world, he abides with a mind rid of longing; he cleanses the mind of longing. [7] With the giving up of ill will and hatred, he abides with a mind rid of ill will, compassionate for the welfare of all creatures and beings; he cleanses the mind of ill will and hatred. With the giving up of indolence-and-lethargy, he abides with a mind rid of indolence-and-lethargy, perceiving light, recollected, and aware; he cleanses the mind of indolence-and-lethargy. With the giving up of restlessness-and-anxiety, he abides without restlessness, his mind internally appeased; he cleanses the mind of restlessness-and-anxiety. With the giving up of doubt, he abides having gone beyond doubt, not uncertain about beneficial qualities; he cleanses the mind of doubt.

He gives up these five hindrances, defilements of the mind that weaken understanding. Then, having thoroughly withdrawn from sensuality, having withdrawn from unbeneficial phenomena, with thinking and with pondering, with joy and ease born of withdrawal, he abides having entered upon the first jhāna. [8] With the appeasement of thinking and pondering, with internal confidence and collectedness of mind, without thinking or pondering and with joy and ease born of composure, he abides having entered upon second jhāna. With the fading of joy, he abides equanimous, recollected, and aware, experiencing ease with the body. He abides having entered upon the third jhāna, with regard to which the noble ones say “one abides equanimous, recollected, and at ease.” With the giving up of ease and unease—and with the ending of joys and upsets beforehand—without ease or unease, with purity of equanimity and remembrance, he abides having entered upon the fourth jhāna.

That is how I instruct the bhikkhus who are trainees—who have not achieved their goal, but live aspiring to the supreme safety from the yoke. But for those bhikkhus who are Arahants—who have destroyed the influxes, fulfilled the training, done what had to be done, laid down the burden, arrived at the highest goal, utterly destroyed the fetters of being, and are liberated by right understanding—these things lead to an easeful abiding in the present experience, and to remembrance-and-awareness.”
#+end_quote
** MN 19
*** Dojč/Döïtshke
#+begin_quote
„Da, ihr Mönche, als ich so achtsam, eifrig und entschlossen verweilte, stieg in mir ein sinnlicher Gedanke auf. Da erkannte ich also: ‚Da ist dieser sinnliche Gedanke in mir aufgestiegen. Er führt zu eigenem Leid, er führt zu fremdem Leid, er führt zu beiderseitigem Leid; er behindert die Weisheit, bringt Beschwerlichkeit mit sich und führt weg vom Nibbāna.‘

Wenn ich, ihr Mönche, bei meiner Überlegung ‚Er führt zu eigenem Leid‘ ihn so durchschaute, verlor er sich.
Wenn ich, ihr Mönche, bei meiner Überlegung ‚Er führt zu fremdem Leid‘ ihn so durchschaute, verlor er sich.
Wenn ich, ihr Mönche, bei meiner Überlegung ‚Er führt zu beiderseitigem Leid‘ ihn so durchschaute, verlor er sich.
Wenn ich, ihr Mönche, bei meiner Überlegung ‚Er behindert die Weisheit, bringt Beschwerlichkeit mit sich und führt weg vom Nibbāna‘ ihn so durchschaute, verlor er sich.“
#+end_quote
*** Pāli
#+begin_quote
“tassa mayhaṃ, bhikkhave, evaṃ appamattassa ātāpino pahitattassa viharato uppajjati kāmavitakko. so evaṃ pajānāmi — ‘uppanno kho me ayaṃ kāmavitakko. so ca kho attabyābādhāyapi saṃvattati, parabyābādhāyapi saṃvattati, ubhayabyābādhāyapi saṃvattati, paññānirodhiko vighātapakkhiko anibbānasaṃvattaniko’ {anibbānasaṃvattaniko””ti (?)} . ‘attabyābādhāya saṃvattatī’tipi me, bhikkhave, paṭisañcikkhato abbhatthaṃ gacchati; ‘parabyābādhāya saṃvattatī’tipi me, bhikkhave, paṭisañcikkhato abbhatthaṃ gacchati; ‘ubhayabyābādhāya saṃvattatī’tipi me, bhikkhave, paṭisañcikkhato abbhatthaṃ gacchati; ‘paññānirodhiko vighātapakkhiko anibbānasaṃvattaniko’tipi me, bhikkhave, paṭisañcikkhato abbhatthaṃ gacchati.
#+end_quote
*** OWTJ
#+begin_quote
As I was living diligent, ardent, and resolute, a thought of sensual
desire arose in me. I understood thus: ‘This thought of sensual desire
has arisen in me. This leads to my own affliction, to others’ affliction,
and to the affliction of both; it obstructs wisdom, causes difficulties,
and leads away from Nibbāna.’ When i considered: ‘This leads to my
own affliction,’ it subsided in me; when i considered: ‘This leads to
others’ affliction,’ it subsided in me; when i considered: ‘This leads
to the affliction of both,’ it subsided in me; when i considered: ‘This
obstructs wisdom, causes difficulties, and leads away from Nibbāna,’ it
subsided in me.
#+end_quote
*** Anigha
#+begin_quote
Then, as I abided heedful, diligent, and resolute, a sensual thought arose. I understood: ‘This sensual thought has arisen for me. It leads to my affliction, to the affliction of others, and to the affliction of both. It blocks understanding, is bound with trouble, and it does not lead to Nibbāna.’ [4] When I considered that it leads to my affliction, it subsided. [5] When I considered that it leads to the affliction of others, it subsided. When I considered that it leads to the affliction of both, it subsided. When I considered that it blocks understanding, is bound with trouble, and does not lead to Nibbāna, it subsided.
#+end_quote

** MN 152
*** Dojč/Döïtshke
#+begin_quote
„Und wie, Ānanda, ist einer ein Edler, der die Fähigkeiten entfaltet? Da, Ānanda, steigt in einem Mönch, der mit dem Auge eine Form gesehen hat, Angenehmes auf, es steigt Unangenehmes auf, es steigt Angenehmes-und-Unangenehmes auf. Wenn er es wünscht: ‚Möge ich beim Abstoßenden eine Wahrnehmung des Nicht-Abstoßenden pflegen‘, so pflegt er genau dort eine Wahrnehmung des Nicht-Abstoßenden. Wenn er es wünscht: ‚Möge ich beim Nicht-Abstoßenden eine Wahrnehmung des Abstoßenden pflegen‘, so pflegt er genau dort eine Wahrnehmung des Abstoßenden. Wenn er es wünscht: ‚Möge ich beim Abstoßenden wie auch beim Nicht-Abstoßenden eine Wahrnehmung des Nicht-Abstoßenden pflegen‘, so pflegt er genau dort eine Wahrnehmung des Nicht-Abstoßenden. Wenn er es wünscht: ‚Möge ich beim Nicht-Abstoßenden wie auch beim Abstoßenden eine Wahrnehmung des Abstoßenden pflegen‘, so pflegt er genau dort eine Wahrnehmung des Abstoßenden. Wenn er es wünscht: ‚Möge ich, indem ich sowohl das Abstoßende als auch das Nicht-Abstoßende beiseite lassend, gleichmütig weilen, achtsam und wissensklar‘, so weilt er genau dort gleichmütig, achtsam und wissensklar.“
#+end_quote
*** Pāli
#+begin_quote
“kathañcānanda, ariyo hoti bhāvitindriyo? idhānanda, bhikkhuno cakkhunā rūpaṃ disvā uppajjati manāpaṃ, uppajjati amanāpaṃ, uppajjati manāpāmanāpaṃ. so sace ākaṅkhati — ‘paṭikūle {paṭikkūle (sabbattha)} appaṭikūlasaññī vihareyyan’ti, appaṭikūlasaññī tattha viharati. sace ākaṅkhati — ‘appaṭikūle paṭikūlasaññī vihareyyan’ti, paṭikūlasaññī tattha viharati. sace ākaṅkhati — ‘paṭikūle ca appaṭikūle ca appaṭikūlasaññī vihareyyan’ti, appaṭikūlasaññī tattha viharati. sace ākaṅkhati — ‘appaṭikūle ca paṭikūle ca paṭikūlasaññī vihareyyan’ti, paṭikūlasaññī tattha viharati. sace ākaṅkhati — ‘paṭikūlañca appaṭikūlañca tadubhayaṃ abhinivajjetvā upekkhako vihareyyaṃ sato sampajāno’ti, upekkhako tattha viharati sato sampajāno.
#+end_quote
*** OWTJ
#+begin_quote
… And how, Ānanda, is one a noble one developing the faculties? here,
Ānanda, in a bhikkhu having seen a form with the eye, there arises
what is pleasant, there arises what is unpleasant, there arises what is
pleasant and unpleasant. If he should wish: ‘May I remain perceiving
the unrepulsive in what is repulsive’, he remains there perceiving the
unrepulsive. If he should wish: ‘May I remain perceiving the repulsive
in what is unrepulsive’, he remains there perceiving the repulsive.
If he should wish: ‘May I remain perceiving the unrepulsive in what
is repulsive and what is unrepulsive’, he remains there perceiving
the unrepulsive. If he should wish: ‘May I remain perceiving the
repulsive in what is repulsive and what is unrepulsive’, he remains
there perceiving the repulsive. If he should wish: ‘May I, surmounting
both what is repulsive and what is unrepulsive, remain equanimous,
recollected and aware’, he remains there equanimous, recollected and
aware …
#+end_quote

** UD 5.5
*** Dojč/Döïtshke
#+begin_quote
„Gleichwie, ihr Mönche, das große Meer eine stufenlose Neigung hat, ein stufenloses Gefälle, eine stufenlose Vertiefung, und nicht jäh abstürzt, so hat auch diese Lehre und Zucht eine gestufte Übung, eine gestufte Ausführung, eine gestufte Praxis, und die Durchdringung zur höheren Erkenntnis geschieht nicht unvermittelt.“
#+end_quote
*** Pāli
#+begin_quote
seyyathāpi, bhikkhave, mahāsamuddo anupubbaninno anupubbapoṇo anupubbapabbhāro, na āyatakeneva papāto; evameva kho, bhikkhave, imasmiṃ dhammavinaye anupubbasikkhā anupubbakiriyā anupubbapaṭipadā, na āyatakeneva aññāpaṭivedho. yampi, bhikkhave, imasmiṃ dhammavinaye anupubbasikkhā anupubbakiriyā anupubbapaṭipadā, na āyatakeneva aññāpaṭivedho
#+end_quote
*** OWTJ
#+begin_quote
Just as the ocean has a gradual shelf, a gradual slope, a gradual
inclination, with a sudden drop-off only after a long stretch, in the
same way this discipline of Dhamma has a gradual training, a gradual
performance, a gradual progression, with attainment of higher
knowledge only after a long stretch.
#+end_quote
** HN 12
*** Dojč/Döïtshke
#+begin_quote
Im Zwischen-Gewebe der Seinsheits-Echos vertieft sich das Eigentliche-wir in die Zeitlichkeit des abschließenden Aufgangs, umhüllend die Kraft des Hier-Kontinuums. Dieser Un-Grund, der eine tiefe Ab-wesenheit-hegt, durchquert das Mit-sein, wo es selbst zum bloßen Geschehnis im ontologischen Schatten des Werdens wird. Doch die Stille des Daseins hallt wider im Meer der Möglichkeiten—wo kein Eigentliches-Anwesen wahrhaft verweilen kann außer in den Murmeln der Zeitlich-Vergänglichkeit. So gibt der vor-ontologische Blick in die Un-Struktur des Seins den Anschein von Sinn—nicht als ob er dem Zugriff des Man-selbst entginge.
#+end_quote
* Chapter 2
** AN 9.41
*** Dojč/Döïtshke
#+begin_quote

#+end_quote

*** Pāli
#+begin_quote
Atha kho āyasmā ānando tapussena gahapatinā saddhiṁ yena bhagavā tenupasaṅkami; upasaṅkamitvā bhagavantaṁ abhivādetvā ekamantaṁ nisīdi. Ekamantaṁ nisinno kho āyasmā ānando bhagavantaṁ etadavoca:
“Ayaṁ, bhante, tapusso gahapati evamāha: ‘mayaṁ, bhante ānanda, gihī kāmabhogino kāmārāmā kāmaratā kāmasammuditā, tesaṁ no, bhante, amhākaṁ gihīnaṁ kāmabhogīnaṁ kāmārāmānaṁ kāmaratānaṁ kāmasammuditānaṁ papāto viya khāyati, yadidaṁ nekkhammaṁ’. Sutaṁ metaṁ, bhante, ‘imasmiṁ dhammavinaye daharānaṁ daharānaṁ bhikkhūnaṁ nekkhamme cittaṁ pakkhandati pasīdati santiṭṭhati vimuccati etaṁ santanti passato. Tayidaṁ, bhante, imasmiṁ dhammavinaye bhikkhūnaṁ bahunā janena visabhāgo yadidaṁ nekkhamman’”ti.
“Evametaṁ, ānanda, evametaṁ, ānanda. Mayhampi kho, ānanda, pubbeva sambodhā anabhisambuddhassa bodhisattasseva sato etadahosi: ‘sādhu nekkhammaṁ, sādhu paviveko’ti. Tassa mayhaṁ, ānanda, nekkhamme cittaṁ na pakkhandati nappasīdati na santiṭṭhati na vimuccati etaṁ santanti passato. Tassa mayhaṁ, ānanda, etadahosi: ‘ko nu kho hetu ko paccayo, yena me nekkhamme cittaṁ na pakkhandati nappasīdati na santiṭṭhati na vimuccati etaṁ santanti passato’? Tassa mayhaṁ, ānanda, etadahosi: ‘kāmesu kho me ādīnavo adiṭṭho, so ca me abahulīkato, nekkhamme ca ānisaṁso anadhigato, so ca me anāsevito. Tasmā me nekkhamme cittaṁ na pakkhandati nappasīdati na santiṭṭhati na vimuccati etaṁ santanti passato’. Tassa mayhaṁ, ānanda, etadahosi: ‘sace kho ahaṁ kāmesu ādīnavaṁ disvā taṁ bahulaṁ kareyyaṁ, nekkhamme ānisaṁsaṁ adhigamma tamāseveyyaṁ, Variant: bahulaṁ kareyyaṁ → bahulīkareyyaṁ (bj, sya-all, pts1ed) ṭhānaṁ kho panetaṁ vijjati yaṁ me nekkhamme cittaṁ pakkhandeyya pasīdeyya santiṭṭheyya vimucceyya etaṁ santanti passato’. So kho ahaṁ, ānanda, aparena samayena kāmesu ādīnavaṁ disvā taṁ bahulamakāsiṁ, nekkhamme ānisaṁsaṁ adhigamma tamāseviṁ. Tassa mayhaṁ, ānanda, nekkhamme cittaṁ pakkhandati pasīdati santiṭṭhati vimuccati etaṁ santanti passato. So kho ahaṁ, ānanda, vivicceva kāmehi vivicca akusalehi dhammehi savitakkaṁ savicāraṁ vivekajaṁ pītisukhaṁ paṭhamaṁ jhānaṁ upasampajja viharāmi. 
#+end_quote
*** OWTJ
#+begin_quote
Then Ven. Ānanda, together with Tapussa the householder, went to
the Blessed One and, on arrival, having bowed down to him, sat to
one side. As he was sitting there he said to the Blessed One: ‘Tapussa
the householder, here, has said to me, “Venerable Ānanda, sir, we
are householders who indulge in sensuality, delight in sensuality,
enjoy sensuality, rejoice in sensuality. For us—indulging in sensuality,
delighting in sensuality, enjoying sensuality, rejoicing in sensuality—
renunciation seems like a sheer drop-off. Yet I’ve heard that in
this teaching and discipline the minds of young monks leap up at
renunciation, grow confident, steadfast, and firm, seeing it as peace.
So right here is where this teaching and discipline is contrary to the
great mass of people: i.e. renunciation.”’
‘So it is, Ānanda. So it is.
Even I myself, before my awakening, when I was still unawakened
but intent upon awakening, thought: “Renunciation is good. Seclusion
is good.” But my mind didn’t leap up at renunciation, didn’t grow
confident, steadfast, or firm, seeing it as peace. The thought occurred
to me: “What is the cause, what is the reason, why my mind doesn’t
leap up at renunciation, doesn’t grow confident, steadfast, or firm,
seeing it as peace?” Then the thought occurred to me:
“i haven’t
seen the danger of sensual pleasures; I haven’t pursued it. I haven’t
understood the reward of renunciation; I haven’t developed it. That’s
why my mind doesn’t leap up at renunciation, doesn’t grow confident,
steadfast, or firm, seeing it as peace.”
Then the thought occurred to me: “If, having seen the danger of
sensual pleasures, I were to pursue that; and if, having understood the
reward of renunciation, I were to develop it, there’s the possibility that
my mind would leap up at renunciation, grow confident, steadfast, and
firm, seeing it as peace.” So at a later time, having seen the danger of
sensual pleasures, I pursued that theme; having understood the reward
of renunciation, I familiarized myself with it. My mind leaped up at
renunciation, grew confident, steadfast, and firm, seeing it as peace.
Then, withdrawn from sensual desires, withdrawn from
unwholesome states, i entered and remained in the first
comprehension: pleasure and happiness born from withdrawal, with
thinking and pondering.’
#+end_quote
*** Anigha
#+begin_quote
Then Venerable Ānanda together with Tapussa approached the Auspicious One, bowed, and sat down to one side. Venerable Ānanda [this translation here says "informed him of the matter", but in the german translation, include the full unabridged version].

“That is exactly how it is, Ānanda. Before my awakening—when I was still unawakened but intent on awakening—I too thought, ‘Renunciation is good! Seclusion is good!’ But my mind did not see renunciation as peaceful, and so it did not leap at it, and was not confident, settled, and liberated in it. Then I thought, ‘What is the cause, what is the reason why my mind does not see renunciation as peaceful, and so it does not leap at it, and is not confident, settled, and liberated in it?’ Then I thought, ‘I have not seen the peril of sensuality, and I have not cultivated that. I have not realized the value of renunciation, and I have not fostered that. That is why my mind does not see renunciation as peaceful, and so does not leap at it, and is not confident, settled, and liberated in it.’ [1] Then I thought, ‘Suppose that, having seen the peril of sensuality, I were to cultivate that. And suppose that, having realized the value of renunciation, I were to foster that. [2] It is possible that, seeing it as peaceful, my mind would leap at renunciation, and be confident, settled, and liberated in it.’ And so, after some time, having seen the peril of sensuality, I cultivated that, and having realized the value of renunciation, I fostered that. Then, seeing it as peaceful, my mind leapt at renunciation, and was confident, settled, and liberated in it. And so, having thoroughly withdrawn from sensuality, having withdrawn from unbeneficial phenomena, with thinking and with pondering, with joy and ease born of withdrawal, I abided having entered upon the first jhāna. 
#+end_quote

** Vin. Kd 16
*** Dojč/Döïtshke
#+begin_quote

#+end_quote
*** Pāli
#+begin_quote
Atha kho bhagavā anāthapiṇḍikassa gahapatissa anupubbiṁ kathaṁ kathesi, seyyathidaṁ—Variant: anupubbiṁ kathaṁ → ānupubbikathaṁ (bj); anupubbikathaṁ (cck, sya1ed, pts1ed); anupubbīkathaṁ (sya2ed) dānakathaṁ sīlakathaṁ saggakathaṁ, kāmānaṁ ādīnavaṁ okāraṁ saṅkilesaṁ, nekkhamme ānisaṁsaṁ pakāsesi. Yadā bhagavā aññāsi anāthapiṇḍikaṁ gahapatiṁ kallacittaṁ muducittaṁ vinīvaraṇacittaṁ udaggacittaṁ pasannacittaṁ, atha yā buddhānaṁ sāmukkaṁsikā dhammadesanā taṁ pakāsesi—dukkhaṁ, samudayaṁ, nirodhaṁ, maggaṁ. Seyyathāpi nāma suddhaṁ vatthaṁ apagatakāḷakaṁ sammadeva rajanaṁ paṭiggaṇheyya; evameva anāthapiṇḍikassa gahapatissa tasmiṁyeva āsane virajaṁ vītamalaṁ dhammacakkhuṁ udapādi—“yaṁ kiñci samudayadhammaṁ sabbaṁ taṁ nirodhadhamman”ti. Atha kho anāthapiṇḍiko gahapati diṭṭhadhammo pattadhammo viditadhammo pariyogāḷhadhammo tiṇṇavicikiccho vigatakathaṅkatho vesārajjappatto aparappaccayo satthusāsane bhagavantaṁ
#+end_quote
*** OWTJ
#+begin_quote
Then the Lord talked a progressive talk to the householder
Anāthapiṇḍika, that is to say talk on giving, talk on moral habit, talk on
heaven, he explained the danger, the vanity, the depravity of pleasures
of the senses, the advantage in renouncing them. When the Lord knew
that the mind of the householder Anāthapiṇḍika was ready, malleable,
devoid of the hindrances, uplifted, pleased, then he explained to him
that teaching on Dhamma which the awakened ones have themselves
discovered: suffering, the origin, the cessation and the way leading to
cessation of suffering. And as a clean cloth without black specks will
easily take dye, even so as he was sitting on that very seat, Dhamma-
vision, dustless, stainless, arose to the householder Anāthapiṇḍika,
that ‘whatever is liable to manifest, all that is liable to cease’. Then the
householder Anāthapiṇḍika, having viewed the Dhamma, reached the
Dhamma, found the Dhamma, plunged into Dhamma, having crossed
over doubt, having put away uncertainty, having become independent
of others in the Teacher’s instruction.
#+end_quote

** MN 125
*** Dojč/Döïtshke
#+begin_quote

#+end_quote
*** Pāli
#+begin_quote
Seyyathāpi, aggivessana, gāmassa vā nigamassa vā avidūre mahāpabbato. Tamenaṁ dve sahāyakā tamhā gāmā vā nigamā vā nikkhamitvā hatthavilaṅghakena yena so pabbato tenupasaṅkameyyuṁ; upasaṅkamitvā eko sahāyako heṭṭhā pabbatapāde tiṭṭheyya, eko sahāyako uparipabbataṁ āroheyya. Tamenaṁ heṭṭhā pabbatapāde ṭhito sahāyako uparipabbate ṭhitaṁ sahāyakaṁ evaṁ vadeyya: ‘yaṁ, samma, kiṁ tvaṁ passasi uparipabbate ṭhito’ti? So evaṁ vadeyya: ‘passāmi kho ahaṁ, samma, uparipabbate ṭhito ārāmarāmaṇeyyakaṁ vanarāmaṇeyyakaṁ bhūmirāmaṇeyyakaṁ pokkharaṇīrāmaṇeyyakan’ti.
So evaṁ vadeyya: ‘aṭṭhānaṁ kho etaṁ, samma, anavakāso yaṁ tvaṁ uparipabbate ṭhito passeyyāsi ārāmarāmaṇeyyakaṁ vanarāmaṇeyyakaṁ bhūmirāmaṇeyyakaṁ pokkharaṇīrāmaṇeyyakan’ti. Tamenaṁ uparipabbate ṭhito sahāyako heṭṭhimapabbatapādaṁ orohitvā taṁ sahāyakaṁ bāhāyaṁ gahetvā uparipabbataṁ āropetvā muhuttaṁ assāsetvā evaṁ vadeyya: ‘yaṁ, samma, kiṁ tvaṁ passasi uparipabbate ṭhito’ti? So evaṁ vadeyya: ‘passāmi kho ahaṁ, samma, uparipabbate ṭhito ārāmarāmaṇeyyakaṁ vanarāmaṇeyyakaṁ bhūmirāmaṇeyyakaṁ pokkharaṇīrāmaṇeyyakan’ti.
So evaṁ vadeyya: ‘idāneva kho te, samma, bhāsitaṁ—mayaṁ evaṁ ājānāma—aṭṭhānaṁ kho etaṁ samma, anavakāso yaṁ tvaṁ uparipabbate ṭhito passeyyāsi ārāmarāmaṇeyyakaṁ vanarāmaṇeyyakaṁ bhūmirāmaṇeyyakaṁ pokkharaṇīrāmaṇeyyakan’ti. Idāneva ca pana te bhāsitaṁ mayaṁ evaṁ ājānāma: ‘passāmi kho ahaṁ, samma, uparipabbate ṭhito ārāmarāmaṇeyyakaṁ vanarāmaṇeyyakaṁ bhūmirāmaṇeyyakaṁ pokkharaṇīrāmaṇeyyakan’ti. So evaṁ vadeyya: ‘tathā hi panāhaṁ, samma, iminā mahatā pabbatena āvuto daṭṭheyyaṁ nāddasan’ti. Variant: āvuto → āvaṭo (bj-a, pts1ed); āvuṭo (sya-all, km, mr)
Ato mahantatarena, aggivessana, ‘avijjākhandhena jayaseno rājakumāro āvuto nivuto ophuṭo pariyonaddho. Variant: nivuto → nivuṭo (sya-all, km, pts1ed, mr) | ophuṭo → ovuto (bj); ovuṭo (sya-all, km, pts1ed) So vata yaṁ taṁ nekkhammena ñātabbaṁ nekkhammena daṭṭhabbaṁ nekkhammena pattabbaṁ nekkhammena sacchikātabbaṁ taṁ vata jayaseno rājakumāro kāmamajjhe vasanto kāme paribhuñjanto kāmavitakkehi khajjamāno kāmapariḷāhena pariḍayhamāno kāmapariyesanāya ussuko ñassati vā dakkhati vā sacchi vā karissatī’ti—netaṁ ṭhānaṁ vijjati.
#+end_quote
*** OWTJ
#+begin_quote
… Aggivessana, it’s as if there were a great mountain and two
companions would go to that mountain. On arrival, one of the
companions would stay at the foot of the mountain, and one would
climb to the top. The companion staying at the foot of the mountain
would ask the companion standing on top, ‘What do you see, my
friend, standing on top of the mountain?’
He would say, ‘I see delightful parks, delightful forests, delightful
stretches of land, and delightful lakes.’
The other would say, ‘It’s impossible, my friend. It cannot happen
that standing on top of the mountain you would see delightful parks,
delightful forests, delightful stretches of land, & delightful lakes.’
Then the companion standing on top, descending to the foot of the
mountain and grabbing his companion by the arm, would make him
climb to the top. After letting him catch his breath for a moment, he
would ask him, ‘What do you see, my friend, standing on top of the
mountain?’
He would say, ‘I see delightful parks, delightful forests, delightful
stretches of land, and delightful lakes.’
The other would say, ‘But just now didn’t you say, “It’s impossible,
my friend. It cannot happen that standing on top of the mountain you
would see delightful parks, delightful forests, delightful stretches of
land, and delightful lakes”? yet now i understand you to say,
“i see
delightful parks, delightful forests, delightful stretches of land, and
delightful lakes.”’
The other would say, ‘But that’s because I was standing blocked by
this great mountain and didn’t see.’
In the same way, Aggivessana, Prince Jayasena is blocked,
obstructed, impeded, and enveloped by the even greater mass of
ignorance. For him, living amid sensuality, enjoying sensuality,
consumed by thoughts of sensuality, burning with the fever of
sensuality, intent on the search for sensuality, to know or see or
realize that which is to be known through renunciation, seen through
renunciation, attained through renunciation, realized through
renunciation: That is impossible. …
#+end_quote

** MN 81
*** Dojč/Döïtshke
#+begin_quote

#+end_quote
*** Pāli
#+begin_quote
“Bhūtapubbaṁ, ānanda, imasmiṁ padese vegaḷiṅgaṁ nāma gāmanigamo ahosi iddho ceva phīto ca bahujano ākiṇṇamanusso. Variant: vegaḷiṅgaṁ → vehaliṅgaṁ (bj); vebhaḷigaṁ (sya-all, km); vebhaḷiṅgaṁ (pts1ed) Vegaḷiṅgaṁ kho, ānanda, gāmanigamaṁ kassapo bhagavā arahaṁ sammāsambuddho upanissāya vihāsi. Idha sudaṁ, ānanda, kassapassa bhagavato arahato sammāsambuddhassa ārāmo ahosi. Idha sudaṁ, ānanda, kassapo bhagavā arahaṁ sammāsambuddho nisinnako bhikkhusaṅghaṁ ovadatī”ti.
Atha kho āyasmā ānando catugguṇaṁ saṅghāṭiṁ paññapetvā bhagavantaṁ etadavoca: “tena hi, bhante, bhagavā nisīdatu ettha. Ayaṁ bhūmipadeso dvīhi arahantehi sammāsambuddhehi paribhutto bhavissatī”ti. Nisīdi bhagavā paññatte āsane. Nisajja kho bhagavā āyasmantaṁ ānandaṁ āmantesi:
“Bhūtapubbaṁ, ānanda, imasmiṁ padese vegaḷiṅgaṁ nāma gāmanigamo ahosi iddho ceva phīto ca bahujano ākiṇṇamanusso. Vegaḷiṅgaṁ kho, ānanda, gāmanigamaṁ kassapo bhagavā arahaṁ sammāsambuddho upanissāya vihāsi. Idha sudaṁ, ānanda, kassapassa bhagavato arahato sammāsambuddhassa ārāmo ahosi. Idha sudaṁ, ānanda, kassapo bhagavā arahaṁ sammāsambuddho nisinnako bhikkhusaṅghaṁ ovadati.
Vegaḷiṅge kho, ānanda, gāmanigame ghaṭikāro nāma kumbhakāro kassapassa bhagavato arahato sammāsambuddhassa upaṭṭhāko ahosi aggupaṭṭhāko. Variant: ghaṭikāro → ghaṭīkāro (bj, cck, pts1ed) Ghaṭikārassa kho, ānanda, kumbhakārassa jotipālo nāma māṇavo sahāyo ahosi piyasahāyo. Atha kho, ānanda, ghaṭikāro kumbhakāro jotipālaṁ māṇavaṁ āmantesi: ‘āyāma, samma jotipāla, kassapaṁ bhagavantaṁ arahantaṁ sammāsambuddhaṁ dassanāya upasaṅkamissāma. Sādhusammatañhi me tassa bhagavato dassanaṁ arahato sammāsambuddhassā’ti.
Evaṁ vutte, ānanda, jotipālo māṇavo ghaṭikāraṁ kumbhakāraṁ etadavoca: ‘alaṁ, samma ghaṭikāra. Kiṁ pana tena muṇḍakena samaṇakena diṭṭhenā’ti?
Dutiyampi kho, ānanda …pe… tatiyampi kho, ānanda, ghaṭikāro kumbhakāro jotipālaṁ māṇavaṁ etadavoca: ‘āyāma, samma jotipāla, kassapaṁ bhagavantaṁ arahantaṁ sammāsambuddhaṁ dassanāya upasaṅkamissāma. Sādhusammatañhi me tassa bhagavato dassanaṁ arahato sammāsambuddhassā’ti.
Tatiyampi kho, ānanda, jotipālo māṇavo ghaṭikāraṁ kumbhakāraṁ etadavoca: ‘alaṁ, samma ghaṭikāra. Kiṁ pana tena muṇḍakena samaṇakena diṭṭhenā’ti?
‘Tena hi, samma jotipāla, sottisināniṁ ādāya nadiṁ gamissāma sināyitun’ti. Variant: ādāya → āhara (mr) | sottisināniṁ → sottiṁ sināniṁ (bj, pts1ed); sottisinānaṁ (sya-all, km, mr)
‘Evaṁ, sammā’ti kho, ānanda, jotipālo māṇavo ghaṭikārassa kumbhakārassa paccassosi. Atha kho, ānanda, ghaṭikāro ca kumbhakāro jotipālo ca māṇavo sottisināniṁ ādāya nadiṁ agamaṁsu sināyituṁ.
Atha kho, ānanda, ghaṭikāro kumbhakāro jotipālaṁ māṇavaṁ āmantesi: ‘ayaṁ, samma jotipāla, kassapassa bhagavato arahato sammāsambuddhassa avidūre ārāmo. Āyāma, samma jotipāla, kassapaṁ bhagavantaṁ arahantaṁ sammāsambuddhaṁ dassanāya upasaṅkamissāma. Sādhusammatañhi me tassa bhagavato dassanaṁ arahato sammāsambuddhassā’ti.
Evaṁ vutte, ānanda, jotipālo māṇavo ghaṭikāraṁ kumbhakāraṁ etadavoca: ‘alaṁ, samma ghaṭikāra. Kiṁ pana tena muṇḍakena samaṇakena diṭṭhenā’ti?
Dutiyampi kho, ānanda …pe… tatiyampi kho, ānanda, ghaṭikāro kumbhakāro jotipālaṁ māṇavaṁ etadavoca: ‘ayaṁ, samma jotipāla, kassapassa bhagavato arahato sammāsambuddhassa avidūre ārāmo. Āyāma, samma jotipāla, kassapaṁ bhagavantaṁ arahantaṁ sammāsambuddhaṁ dassanāya upasaṅkamissāma. Sādhusammatañhi me tassa bhagavato dassanaṁ arahato sammāsambuddhassā’ti.
Tatiyampi kho, ānanda, jotipālo māṇavo ghaṭikāraṁ kumbhakāraṁ etadavoca: ‘alaṁ, samma ghaṭikāra. Kiṁ pana tena muṇḍakena samaṇakena diṭṭhenā’ti?
Atha kho, ānanda, ghaṭikāro kumbhakāro jotipālaṁ māṇavaṁ ovaṭṭikāyaṁ parāmasitvā etadavoca: ‘ayaṁ, samma jotipāla, kassapassa bhagavato arahato sammāsambuddhassa avidūre ārāmo. Āyāma, samma jotipāla, kassapaṁ bhagavantaṁ arahantaṁ sammāsambuddhaṁ dassanāya upasaṅkamissāma. Sādhusammatañhi me tassa bhagavato dassanaṁ arahato sammāsambuddhassā’ti.
Atha kho, ānanda, jotipālo māṇavo ovaṭṭikaṁ vinivaṭṭetvā ghaṭikāraṁ kumbhakāraṁ etadavoca: Variant: vinivaṭṭetvā → viniveṭhetvā (bj, sya1ed, sya2ed, km, pts1ed); vinivedhetvā (cck) ‘alaṁ, samma ghaṭikāra. Kiṁ pana tena muṇḍakena samaṇakena diṭṭhenā’ti?
Atha kho, ānanda, ghaṭikāro kumbhakāro jotipālaṁ māṇavaṁ sīsaṁnhātaṁ kesesu parāmasitvā etadavoca: Variant: sīsaṁnhātaṁ → sasīsaṁ nahātaṁ (bj); sīsanhātaṁ (sya-all, km); sīsanahātaṁ (pts1ed) ‘ayaṁ, samma jotipāla, kassapassa bhagavato arahato sammāsambuddhassa avidūre ārāmo. Āyāma, samma jotipāla, kassapaṁ bhagavantaṁ arahantaṁ sammāsambuddhaṁ dassanāya upasaṅkamissāma. Sādhusammatañhi me tassa bhagavato dassanaṁ arahato sammāsambuddhassā’ti.
Atha kho, ānanda, jotipālassa māṇavassa etadahosi: ‘acchariyaṁ vata bho, abbhutaṁ vata bho. Yatra hi nāmāyaṁ ghaṭikāro kumbhakāro ittarajacco samāno amhākaṁ sīsaṁnhātānaṁ kesesu parāmasitabbaṁ maññissati; na vatidaṁ kira orakaṁ maññe bhavissatī’ti; ghaṭikāraṁ kumbhakāraṁ etadavoca: ‘yāvatādohipi, samma ghaṭikārā’ti? Variant: yāvatādohipi → yāvetadohipi (bj, sya-all, km, pts1ed)
‘Yāvatādohipi, samma jotipāla. Tathā hi pana me sādhusammataṁ tassa bhagavato dassanaṁ arahato sammāsambuddhassā’ti.
‘Tena hi, samma ghaṭikāra, muñca; gamissāmā’ti.
Atha kho, ānanda, ghaṭikāro ca kumbhakāro jotipālo ca māṇavo yena kassapo bhagavā arahaṁ sammāsambuddho tenupasaṅkamiṁsu; upasaṅkamitvā ghaṭikāro kumbhakāro kassapaṁ bhagavantaṁ arahantaṁ sammāsambuddhaṁ abhivādetvā ekamantaṁ nisīdi. Jotipālo pana māṇavo kassapena bhagavatā arahatā sammāsambuddhena saddhiṁ sammodi. Sammodanīyaṁ kathaṁ sāraṇīyaṁ vītisāretvā ekamantaṁ nisīdi.
Ekamantaṁ nisinno kho, ānanda, ghaṭikāro kumbhakāro kassapaṁ bhagavantaṁ arahantaṁ sammāsambuddhaṁ etadavoca: ‘ayaṁ me, bhante, jotipālo māṇavo sahāyo piyasahāyo. Imassa bhagavā dhammaṁ desetū’ti. Atha kho, ānanda, kassapo bhagavā arahaṁ sammāsambuddho ghaṭikārañca kumbhakāraṁ jotipālañca māṇavaṁ dhammiyā kathāya sandassesi samādapesi samuttejesi sampahaṁsesi. Atha kho, ānanda, ghaṭikāro ca kumbhakāro jotipālo ca māṇavo kassapena bhagavatā arahatā sammāsambuddhena dhammiyā kathāya sandassitā samādapitā samuttejitā sampahaṁsitā kassapassa bhagavato arahato sammāsambuddhassa bhāsitaṁ abhinanditvā anumoditvā uṭṭhāyāsanā kassapaṁ bhagavantaṁ arahantaṁ sammāsambuddhaṁ abhivādetvā padakkhiṇaṁ katvā pakkamiṁsu.
Atha kho, ānanda, jotipālo māṇavo ghaṭikāraṁ kumbhakāraṁ etadavoca: ‘imaṁ nu tvaṁ, samma ghaṭikāra, dhammaṁ suṇanto atha ca pana agārasmā anagāriyaṁ na pabbajissasī’ti?
‘Nanu maṁ, samma jotipāla, jānāsi, andhe jiṇṇe mātāpitaro posemī’ti?
‘Tena hi, samma ghaṭikāra, ahaṁ agārasmā anagāriyaṁ pabbajissāmī’ti.
Atha kho, ānanda, ghaṭikāro ca kumbhakāro jotipālo ca māṇavo yena kassapo bhagavā arahaṁ sammāsambuddho tenupasaṅkamiṁsu; upasaṅkamitvā kassapaṁ bhagavantaṁ arahantaṁ sammāsambuddhaṁ abhivādetvā ekamantaṁ nisīdiṁsu. Ekamantaṁ nisinno kho, ānanda, ghaṭikāro kumbhakāro kassapaṁ bhagavantaṁ arahantaṁ sammāsambuddhaṁ etadavoca: ‘ayaṁ me, bhante, jotipālo māṇavo sahāyo piyasahāyo. Imaṁ bhagavā pabbājetū’ti. Alattha kho, ānanda, jotipālo māṇavo kassapassa bhagavato arahato sammāsambuddhassa santike pabbajjaṁ, alattha upasampadaṁ.
Atha kho, ānanda, kassapo bhagavā arahaṁ sammāsambuddho acirūpasampanne jotipāle māṇave aḍḍhamāsupasampanne vegaḷiṅge yathābhirantaṁ viharitvā yena bārāṇasī tena cārikaṁ pakkāmi. Anupubbena cārikaṁ caramāno yena bārāṇasī tadavasari. Tatra sudaṁ, ānanda, kassapo bhagavā arahaṁ sammāsambuddho bārāṇasiyaṁ viharati isipatane migadāye. Assosi kho, ānanda, kikī kāsirājā: ‘kassapo kira bhagavā arahaṁ sammāsambuddho bārāṇasiṁ anuppatto bārāṇasiyaṁ viharati isipatane migadāye’ti. Atha kho, ānanda, kikī kāsirājā bhadrāni bhadrāni yānāni yojāpetvā bhadraṁ yānaṁ abhiruhitvā bhadrehi bhadrehi yānehi bārāṇasiyā niyyāsi mahaccarājānubhāvena kassapaṁ bhagavantaṁ arahantaṁ sammāsambuddhaṁ dassanāya. Variant: bhadrāni yānāni yojāpetvā bhadraṁ → bhadraṁ bhadraṁ (mr) Yāvatikā yānassa bhūmi yānena gantvā yānā paccorohitvā pattikova yena kassapo bhagavā arahaṁ sammāsambuddho tenupasaṅkami; upasaṅkamitvā kassapaṁ bhagavantaṁ arahantaṁ sammāsambuddhaṁ abhivādetvā ekamantaṁ nisīdi. Ekamantaṁ nisinnaṁ kho, ānanda, kikiṁ kāsirājānaṁ kassapo bhagavā arahaṁ sammāsambuddho dhammiyā kathāya sandassesi samādapesi samuttejesi sampahaṁsesi.
Atha kho, ānanda, kikī kāsirājā kassapena bhagavatā arahatā sammāsambuddhena dhammiyā kathāya sandassito samādapito samuttejito sampahaṁsito kassapaṁ bhagavantaṁ arahantaṁ sammāsambuddhaṁ etadavoca: ‘adhivāsetu me, bhante, bhagavā svātanāya bhattaṁ saddhiṁ bhikkhusaṅghenā’ti. Adhivāsesi kho, ānanda, kassapo bhagavā arahaṁ sammāsambuddho tuṇhībhāvena.
Atha kho, ānanda, kikī kāsirājā kassapassa bhagavato sammāsambuddhassa adhivāsanaṁ viditvā uṭṭhāyāsanā kassapaṁ bhagavantaṁ arahantaṁ sammāsambuddhaṁ abhivādetvā padakkhiṇaṁ katvā pakkāmi. Atha kho, ānanda, kikī kāsirājā tassā rattiyā accayena sake nivesane paṇītaṁ khādanīyaṁ bhojanīyaṁ paṭiyādāpetvā paṇḍupuṭakassa sālino vigatakāḷakaṁ anekasūpaṁ anekabyañjanaṁ, kassapassa bhagavato arahato sammāsambuddhassa kālaṁ ārocāpesi: Variant: paṇḍupuṭakassa → paṇḍumuṭikassa (bj, pts1ed); paṇḍumudikassa (sya-all, km) ‘kālo, bhante, niṭṭhitaṁ bhattan’ti.
Atha kho, ānanda, kassapo bhagavā arahaṁ sammāsambuddho pubbaṇhasamayaṁ nivāsetvā pattacīvaramādāya yena kikissa kāsirañño nivesanaṁ tenupasaṅkami; upasaṅkamitvā paññatte āsane nisīdi saddhiṁ bhikkhusaṅghena. Atha kho, ānanda, kikī kāsirājā buddhappamukhaṁ bhikkhusaṅghaṁ paṇītena khādanīyena bhojanīyena sahatthā santappesi sampavāresi.
Atha kho, ānanda, kikī kāsirājā kassapaṁ bhagavantaṁ arahantaṁ sammāsambuddhaṁ bhuttāviṁ onītapattapāṇiṁ aññataraṁ nīcaṁ āsanaṁ gahetvā ekamantaṁ nisīdi. Ekamantaṁ nisinno kho, ānanda, kikī kāsirājā kassapaṁ bhagavantaṁ arahantaṁ sammāsambuddhaṁ etadavoca: ‘adhivāsetu me, bhante, bhagavā bārāṇasiyaṁ vassāvāsaṁ; evarūpaṁ saṅghassa upaṭṭhānaṁ bhavissatī’ti.
‘Alaṁ, mahārāja. Adhivuttho me vassāvāso’ti.
Dutiyampi kho, ānanda … tatiyampi kho, ānanda, kikī kāsirājā kassapaṁ bhagavantaṁ arahantaṁ sammāsambuddhaṁ etadavoca: ‘adhivāsetu me, bhante, bhagavā bārāṇasiyaṁ vassāvāsaṁ; evarūpaṁ saṅghassa upaṭṭhānaṁ bhavissatī’ti.
‘Alaṁ, mahārāja. Adhivuttho me vassāvāso’ti.
Atha kho, ānanda, kikissa kāsirañño ‘na me kassapo bhagavā arahaṁ sammāsambuddho adhivāseti bārāṇasiyaṁ vassāvāsan’ti ahudeva aññathattaṁ, ahu domanassaṁ. Atha kho, ānanda, kikī kāsirājā kassapaṁ bhagavantaṁ arahantaṁ sammāsambuddhaṁ etadavoca: ‘atthi nu kho, bhante, añño koci mayā upaṭṭhākataro’ti?
‘Atthi, mahārāja, vegaḷiṅgaṁ nāma gāmanigamo. Tattha ghaṭikāro nāma kumbhakāro; so me upaṭṭhāko aggupaṭṭhāko. Tuyhaṁ kho pana, mahārāja, na me kassapo bhagavā arahaṁ sammāsambuddho adhivāseti bārāṇasiyaṁ vassāvāsanti attheva aññathattaṁ, atthi domanassaṁ. Variant: attheva → atthi (bj, pts1ed) Tayidaṁ ghaṭikārassa kumbhakārassa natthi ca na ca bhavissati. Variant: ghaṭikārassa kumbhakārassa → ghaṭikāre kumbhakāre (bj, sya1ed, sya2ed, km); ghaṭīkāre kumbhakāre (cck, pts1ed)
Ghaṭikāro kho, mahārāja, kumbhakāro buddhaṁ saraṇaṁ gato, dhammaṁ saraṇaṁ gato, saṅghaṁ saraṇaṁ gato. Ghaṭikāro kho, mahārāja, kumbhakāro pāṇātipātā paṭivirato, adinnādānā paṭivirato, kāmesumicchācārā paṭivirato, musāvādā paṭivirato, surāmerayamajjapamādaṭṭhānā paṭivirato. Ghaṭikāro kho, mahārāja, kumbhakāro buddhe aveccappasādena samannāgato, dhamme aveccappasādena samannāgato, saṅghe aveccappasādena samannāgato, ariyakantehi sīlehi samannāgato. Ghaṭikāro kho, mahārāja, kumbhakāro dukkhe nikkaṅkho, dukkhasamudaye nikkaṅkho, dukkhanirodhe nikkaṅkho, dukkhanirodhagāminiyā paṭipadāya nikkaṅkho. Ghaṭikāro kho, mahārāja, kumbhakāro ekabhattiko brahmacārī sīlavā kalyāṇadhammo. Ghaṭikāro kho, mahārāja, kumbhakāro nikkhittamaṇisuvaṇṇo apetajātarūparajato. Ghaṭikāro kho, mahārāja, kumbhakāro pannamusalo na sahatthā pathaviṁ khaṇati. Variant: kumbhakāro pannamusalo na sahatthā pathaviṁ khaṇati → kumbhakāro na musalena na sahatthā paṭhaviñca khanati (sya-all, km); kumbhakāro na musalena na sahatthā paṭhaviṁ khaṇati (pts1ed); kumbhakāro na musalena sahatthā pathaviñca khaṇati (mr) Yaṁ hoti kūlapaluggaṁ vā mūsikukkaro vā taṁ kājena āharitvā bhājanaṁ karitvā evamāha: Variant: mūsikukkaro → mūsikukkāro (bj); mūsikukkuro (si, sya-all, km, pts1ed) “ettha yo icchati taṇḍulapaṭibhastāni vā muggapaṭibhastāni vā kaḷāyapaṭibhastāni vā nikkhipitvā yaṁ icchati taṁ haratū”ti. Ghaṭikāro kho, mahārāja, kumbhakāro andhe jiṇṇe mātāpitaro poseti. Ghaṭikāro kho, mahārāja, kumbhakāro pañcannaṁ orambhāgiyānaṁ saṁyojanānaṁ parikkhayā opapātiko tattha parinibbāyī anāvattidhammo tasmā lokā.
Ekamidāhaṁ, mahārāja, samayaṁ vegaḷiṅge nāma gāmanigame viharāmi. Atha khvāhaṁ, mahārāja, pubbaṇhasamayaṁ nivāsetvā pattacīvaramādāya yena ghaṭikārassa kumbhakārassa mātāpitaro tenupasaṅkamiṁ; upasaṅkamitvā ghaṭikārassa kumbhakārassa mātāpitaro etadavocaṁ: “handa ko nu kho ayaṁ bhaggavo gato”ti?
“Nikkhanto kho te, bhante, upaṭṭhāko antokumbhiyā odanaṁ gahetvā pariyogā sūpaṁ gahetvā paribhuñjā”ti. Atha khvāhaṁ, mahārāja, kumbhiyā odanaṁ gahetvā pariyogā sūpaṁ gahetvā paribhuñjitvā uṭṭhāyāsanā pakkamiṁ. Variant: pakkamiṁ → pakkāmiṁ (sya-all, km, pts1ed)
Atha kho, mahārāja, ghaṭikāro kumbhakāro yena mātāpitaro tenupasaṅkami; upasaṅkamitvā mātāpitaro etadavoca: “ko kumbhiyā odanaṁ gahetvā pariyogā sūpaṁ gahetvā paribhuñjitvā uṭṭhāyāsanā pakkanto”ti?
“Kassapo, tāta, bhagavā arahaṁ sammāsambuddho kumbhiyā odanaṁ gahetvā pariyogā sūpaṁ gahetvā paribhuñjitvā uṭṭhāyāsanā pakkanto”ti?
Atha kho, mahārāja, ghaṭikārassa kumbhakārassa etadahosi: “lābhā vata me, suladdhaṁ vata me, yassa me kassapo bhagavā arahaṁ sammāsambuddho evaṁ abhivissattho”ti. Atha kho, mahārāja, ghaṭikāraṁ kumbhakāraṁ aḍḍhamāsaṁ pītisukhaṁ na vijahati, sattāhaṁ mātāpitūnaṁ. Variant: na vijahati → na vijahi (bj, sya-all, km, pts1ed)
Ekamidāhaṁ, mahārāja, samayaṁ tattheva vegaḷiṅge nāma gāmanigame viharāmi. Atha khvāhaṁ, mahārāja, pubbaṇhasamayaṁ nivāsetvā pattacīvaramādāya yena ghaṭikārassa kumbhakārassa mātāpitaro tenupasaṅkamiṁ; upasaṅkamitvā ghaṭikārassa kumbhakārassa mātāpitaro etadavocaṁ: “handa ko nu kho ayaṁ bhaggavo gato”ti?
“Nikkhanto kho te, bhante, upaṭṭhāko anto kaḷopiyā kummāsaṁ gahetvā pariyogā sūpaṁ gahetvā paribhuñjā”ti. Atha khvāhaṁ, mahārāja, kaḷopiyā kummāsaṁ gahetvā pariyogā sūpaṁ gahetvā paribhuñjitvā uṭṭhāyāsanā pakkamiṁ.
Atha kho, mahārāja, ghaṭikāro kumbhakāro yena mātāpitaro tenupasaṅkami; upasaṅkamitvā mātāpitaro etadavoca: “ko kaḷopiyā kummāsaṁ gahetvā pariyogā sūpaṁ gahetvā paribhuñjitvā uṭṭhāyāsanā pakkanto”ti?
“Kassapo, tāta, bhagavā arahaṁ sammāsambuddho kaḷopiyā kummāsaṁ gahetvā pariyogā sūpaṁ gahetvā paribhuñjitvā uṭṭhāyāsanā pakkanto”ti.
Atha kho, mahārāja, ghaṭikārassa kumbhakārassa etadahosi: “lābhā vata me, suladdhaṁ vata me, yassa me kassapo bhagavā arahaṁ sammāsambuddho evaṁ abhivissattho”ti. Atha kho, mahārāja, ghaṭikāraṁ kumbhakāraṁ aḍḍhamāsaṁ pītisukhaṁ na vijahati, sattāhaṁ mātāpitūnaṁ.
Ekamidāhaṁ, mahārāja, samayaṁ tattheva vegaḷiṅge nāma gāmanigame viharāmi. Tena kho pana samayena kuṭi ovassati. Variant: kuṭi → gandhakuṭi (bj); kuṭī (pts1ed) Atha khvāhaṁ, mahārāja, bhikkhū āmantesiṁ:
“gacchatha, bhikkhave, ghaṭikārassa kumbhakārassa nivesane tiṇaṁ jānāthā”ti.
Evaṁ vutte, mahārāja, te bhikkhū maṁ etadavocuṁ: “natthi kho, bhante, ghaṭikārassa kumbhakārassa nivesane tiṇaṁ, atthi ca khvāssa āvesane tiṇacchadanan”ti. Variant: āvesane → āvesanaṁ (bj, sya-all, km, pts1ed)
“Gacchatha, bhikkhave, ghaṭikārassa kumbhakārassa āvesanaṁ uttiṇaṁ karothā”ti. Atha kho te, mahārāja, bhikkhū ghaṭikārassa kumbhakārassa āvesanaṁ uttiṇamakaṁsu.
Atha kho, mahārāja, ghaṭikārassa kumbhakārassa mātāpitaro te bhikkhū etadavocuṁ: “ke āvesanaṁ uttiṇaṁ karontī”ti?
“Bhikkhū, bhagini, kassapassa bhagavato arahato sammāsambuddhassa kuṭi ovassatī”ti.
“Haratha, bhante, haratha, bhadramukhā”ti.
Atha kho, mahārāja, ghaṭikāro kumbhakāro yena mātāpitaro tenupasaṅkami; upasaṅkamitvā mātāpitaro etadavoca: “ke āvesanaṁ uttiṇamakaṁsū”ti?
“Bhikkhū, tāta, kassapassa kira bhagavato arahato sammāsambuddhassa kuṭi ovassatī”ti.
Atha kho, mahārāja, ghaṭikārassa kumbhakārassa etadahosi: “lābhā vata me, suladdhaṁ vata me, yassa me kassapo bhagavā arahaṁ sammāsambuddho evaṁ abhivissattho”ti. Atha kho, mahārāja, ghaṭikāraṁ kumbhakāraṁ aḍḍhamāsaṁ pītisukhaṁ na vijahati, sattāhaṁ mātāpitūnaṁ.
Atha kho, mahārāja, āvesanaṁ sabbantaṁ temāsaṁ ākāsacchadanaṁ aṭṭhāsi, na devotivassi. Variant: na devotivassi → na cātivassi (bj, sya-all, km, pts1ed) Evarūpo ca, mahārāja, ghaṭikāro kumbhakāro’ti.
‘Lābhā, bhante, ghaṭikārassa kumbhakārassa, suladdhā, bhante, ghaṭikārassa kumbhakārassa yassa bhagavā evaṁ abhivissattho’ti.
Atha kho, ānanda, kikī kāsirājā ghaṭikārassa kumbhakārassa pañcamattāni taṇḍulavāhasatāni pāhesi paṇḍupuṭakassa sālino tadupiyañca sūpeyyaṁ. Atha kho te, ānanda, rājapurisā ghaṭikāraṁ kumbhakāraṁ upasaṅkamitvā etadavocuṁ: ‘imāni kho, bhante, pañcamattāni taṇḍulavāhasatāni kikinā kāsirājena pahitāni paṇḍupuṭakassa sālino tadupiyañca sūpeyyaṁ. Tāni, bhante, paṭiggaṇhathā’ti. Variant: paṭiggaṇhathā’ti → patigaṇhātūti (bj, pts1ed); paṭiggaṇhātūti (sya-all, km)
‘Rājā kho bahukicco bahukaraṇīyo. Alaṁ me. Raññova hotū’ti.
Siyā kho pana te, ānanda, evamassa: ‘añño nūna tena samayena jotipālo māṇavo ahosī’ti. Na kho panetaṁ, ānanda, evaṁ daṭṭhabbaṁ. Ahaṁ tena samayena jotipālo māṇavo ahosin”ti.
Idamavoca bhagavā. Attamano āyasmā ānando bhagavato bhāsitaṁ abhinandīti.
#+end_quote
*** OWTJ
#+begin_quote
Once, Ānanda, there was a market town in this spot named
Vebhaliṅga. it was prosperous and full of people. And Kassapa, a
blessed one, a perfected one, a fully awakened Buddha, lived supported
by Vebhaliṅga. it was here, in fact, that he had his monastery, where
he sat and advised the mendicant Saṅgha.
The Buddha Kassapa had as a chief supporter in Vebhaliṅga a
potter named Ghaṭīkāra. Ghaṭīkāra had a dear friend named Jotipāla, a
brahmin student.
Then Ghaṭīkāra addressed Jotipāla, ‘Come, dear Jotipāla, let’s go to
see the Blessed One Kassapa, the perfected one, the fully awakened
Buddha. For I regard it as holy to see that Blessed One.’ When he said
this, Jotipāla said to him,
‘Enough, what’s the use of seeing that bald,
fake ascetic?’
For a second time … and a third time, Ghaṭīkāra addressed Jotipāla,
‘Come, dear Jotipāla, let’s go to see the Blessed One Kassapa, the
perfected one, the fully awakened Buddha. For I regard it as holy to
see that Blessed One.’ for a third time, Jotipāla said to him,
‘Enough,
what’s the use of seeing that bald, fake ascetic?’
–
‘Well then, Jotipāla,
let’s take some bathing paste of powdered shell and go to the river to
bathe.’
–
‘Yes’ replied Jotipāla.
So that’s what they did. Then Ghaṭīkāra addressed Jotipāla, ‘Jotipāla,
the Buddha Kassapa’s monastery is not far away. let’s go to see the
Blessed One Kassapa, the perfected one, the fully awakened Buddha.
For I regard it as holy to see that Blessed One.’ When he said this,
Jotipāla said to him,
‘Enough, what’s the use of seeing that bald, fake
ascetic?’
For a second time … and a third time, Ghaṭīkāra addressed Jotipāla,
‘Dear Jotipāla, the Buddha Kassapa’s monastery is not far away.
Let’s go to see the Blessed One Kassapa, the perfected one, the fully
awakened Buddha. For I regard it as holy to see that Blessed One.’ For a
third time, Jotipāla said to him,
‘Enough, what’s the use of seeing that
bald, fake ascetic?’
Then Ghaṭīkāra grabbed Jotipāla by the belt and repeated his
request. … So Jotipāla undid his belt and said to Ghaṭīkāra,
‘Enough,
what’s the use of seeing that bald, fake ascetic?’
Then Ghaṭīkāra grabbed Jotipāla by the hair of his freshly-washed
head repeated his request. …
Then Jotipāla thought,
‘It’s incredible, it’s amazing, how this potter
Ghaṭikāra, though born in a lower caste, should presume to grab me by
the hair of my freshly-washed head! This must be no ordinary matter.’
He said to Ghaṭīkāra,
‘You’d even milk it to this extent, Ghaṭīkāra?’
–
‘i
even milk it to this extent, Jotipāla. for that is how holy i regard it to
see that Blessed One.’
–
‘Well then, Ghaṭīkāra, release me, we shall go.’
Then Ghaṭīkāra the potter and Jotipāla the brahmin student went
to the Buddha Kassapa. Ghaṭīkāra bowed and sat down to one side, but
Jotipāla exchanged greetings with the Buddha and sat down to one
side. Ghaṭīkāra said to the Buddha Kassapa, ‘Sir, this is my dear friend
Jotipāla, a brahmin student. Please teach him the Dhamma.’
Then the Buddha Kassapa educated, encouraged, fired up, and
inspired Ghaṭikāra and Jotipāla with a Dhamma talk. Then they got up
from their seat, bowed, and respectfully circled the Buddha Kassapa,
keeping him on their right, before leaving.
Then Jotipāla said to Ghatīkāra, ‘Ghaṭīkāra, you have heard this
teaching, so why don’t you go forth from the lay life to homelessness?’
–
‘Don’t you know, Jotipāla, that i look after my blind old parents?’
–
‘Well then, Ghaṭīkāra, i shall go forth from the lay life to homelessness.’
Then Ghaṭīkāra and Jotipāla went to the Buddha Kassapa, bowed,
and sat down to one side. Ghaṭīkāra said to the Buddha Kassapa, ‘Sir,
this is my dear friend Jotipāla, a brahmin student. Please give him
the going forth.’ And Jotipāla the brahmin student received the going
forth, the ordination in the Buddha’s presence.
Not long after Jotipāla’s ordination, a fortnight later, the Buddha
Kassapa—having stayed in Vebhaliṅga as long as he wished—set out
for Benares. Travelling stage by stage, he arrived at Benares, where he
stayed near Benares, in the deer park at Isipatana.
The King of Kāsi heard that he had arrived. he had the finest
carriages harnessed. he then mounted a fine carriage and, along with
other fine carriages, set out in full royal pomp from Benares to see
the Buddha Kassapa. he went by carriage as far as the terrain allowed,
then descended and approached the Buddha Kassapa on foot. he
bowed and sat down to one side. The Buddha educated, encouraged,
fired up, and inspired him with a Dhamma talk.
Then the King said to the Buddha, ‘Sir, would the Buddha together
with the bhikkhu Saṅgha please accept tomorrow’s meal from me?’
The Buddha Kassapa consented in silence. Then, knowing that the
Buddha had consented, the King got up from his seat, bowed, and
respectfully circled the Buddha, keeping him on his right, before
leaving.
And when the night had passed, the King had a variety of delicious
foods prepared in his own home—soft saffron rice with the dark grains
picked out, served with many soups and sauces. Then he had the
Buddha informed of the time, saying, ‘Sir, it’s time. The meal is ready.’
Then Kassapa Buddha robed up in the morning and, taking his
bowl and robe, went to the home of the King, where he sat on the
seat spread out, together with the Saṅgha of bhikkhus. Then the King
served and satisfied the bhikkhu Saṅgha headed by the Buddha with
his own hands with a variety of delicious foods. When the Buddha
Kassapa had eaten and washed his hand and bowl, the King took a low
seat and sat to one side. There he said to the Buddha Kassapa, ‘Sir,
may the Buddha please accept my invitation to reside in Benares for
the rainy season. The Saṅgha will be looked after in the same style.’
–
‘Enough, great king. I have already accepted an invitation for the rains
residence.’
For a second time … and a third time the King said to the Buddha
Kassapa, ‘Sir, may the Buddha please accept my invitation to reside
in Benares for the rainy season. The Saṅgha will be looked after in
the same style.’
–
‘Enough, Great King. i have already accepted an
invitation for the rains residence.’
Then the King, thinking, ‘The Buddha does not accept my invitation
to reside for the rains in Benares,’ became sad and upset.
Then the King said to the Buddha Kassapa, ‘Sir, do you have
another supporter better than me?’
–
‘Great king, there is a market
town named Vebhaliṅga, where there’s a potter named Ghaṭīkāra.
He is my chief supporter. Now, great king, you thought, “The Buddha
does not accept my invitation to reside for the rains in Benares,”
and you became sad and upset. But Ghaṭīkāra doesn’t get upset, nor
will he. Ghaṭīkāra has gone for refuge to the Buddha, the teaching,
and the Saṅgha. he doesn’t kill living creatures, steal, commit sexual
misconduct, lie, or take alcoholic drinks that cause negligence. He
has experiential confidence in the Buddha, the teaching, and the
Saṅgha, and has virtues praised by the noble ones. he is free of doubt
regarding suffering, its origin, its cessation, and the practice that leads
to its cessation. He eats in one part of the day; he’s celibate, virtuous,
and of good character. He has set aside gems and gold and rejected
gold and money. He’s put down the shovel and doesn’t dig the earth
with his own hands. He takes what has crumbled off by a riverbank
or been dug up by mice, and brings it back in a carrier. When he has
made a pot, he says, “Anyone may leave bagged sesame, mung beans,
or chickpeas here and take what they wish.” He looks after his blind
old parents. And since he has ended the five lower fetters, Ghaṭīkāra
will be born in a heavenly realm and will become extinguished there,
not liable to return from that world.
This one time, great king, I was staying near the market town of
Vebhaliṅga. Then i robed up in the morning and, taking my bowl and
robe, went to the home of Ghaṭīkāra’s parents, where i said to them,
“Excuse me, where has Ghaṭīkāra gone?”
–
“Your supporter has gone
out, sir. But take rice from the pot and sauce from the pan and eat.”
So that’s what I did. And after eating I got up from my seat and left.
–
Then Ghaṭīkāra went up to his parents and said, “Who took rice from
the pot and sauce from the pan, ate it, and left?”
–
“It was the Buddha
Kassapa, my dear.”
Then Ghaṭīkāra thought,
“I’m so fortunate, so very fortunate, in
that the Buddha Kassapa trusts me so much!” Then joy and happiness
did not leave him for a fortnight, or his parents for a week.
Another time, great king, I was staying near that same market town
of Vebhaliṅga. Then i robed up in the morning and, taking my bowl
and robe, went to the home of Ghaṭīkāra’s parents, where i said to
them,
“Excuse me, where has Ghaṭīkāra gone?”
–
“Your supporter has
gone out, sir. But take porridge from the pot and sauce from the pan
and eat.”
So that’s what I did. And after eating I got up from my seat and left.
Then Ghaṭīkāra went up to his parents and said, “Who took porridge
from the pot and sauce from the pan, ate it, and left?”
–
“It was the
Buddha Kassapa, my dear.”
Then Ghaṭīkāra thought,
“I’m so fortunate, so very fortunate, to be
trusted so much by the Buddha Kassapa!” Then joy and happiness did
not leave him for a fortnight, or his parents for a week.
Another time, great king, I was staying near that same market town
of Vebhaliṅga. Now at that time my hut leaked. So i addressed the
bhikkhus, “Bhikkhus, go to Ghaṭikāra’s home and find some grass.”
–
When i said this, those bhikkhus said to me, “Sir, there’s no grass
there, but his workshop has a grass roof.”
–
“Then go to the workshop
and strip the grass.”
So that’s what they did. Then Ghaṭīkāra’s parents said to those
bhikkhus, “Who’s stripping the grass from the workshop?”
–
“It’s the
bhikkhus, sister. The Buddha’s hut is leaking.”
–
“Take it, sirs! Take it!”
Then Ghaṭīkāra went up to his parents and said, “Who stripped the
grass from the workshop?”
–
“It was the bhikkhus, dear. it seems the
Buddha’s hut is leaking.”
Then Ghaṭīkāra thought,
“I’m so fortunate, so very fortunate, to
be trusted so much by the Buddha Kassapa!” Then joy and happiness
did not leave him for a fortnight, or his parents for a week. Then
the workshop remained with the sky for a roof for the whole three
months, but no rain fell on it. And that, great king, is what Ghaṭīkāra
the potter is like.’
‘Ghaṭīkāra the potter is fortunate, very fortunate, to be so trusted
by the Buddha Kassapa.’
Then the King sent around five hundred cartloads of rice, soft
saffron rice, and suitable sauce to Ghaṭīkāra. Then one of the king’s
men approached Ghaṭīkāra and said, ‘Sir, these five hundred cartloads
of rice, soft saffron rice, and suitable sauce have been sent to you by
the King of Kāsī. Please accept them.’
–
‘The king has many duties, and
much to do. I have enough. Let this be for the king himself.’
Ānanda, you might think: ‘Surely the brahmin student Jotipāla must
have been someone else at that time?’ But you should not see it like
this. i was the student Jotipāla at that time.”
That is what the Buddha said. Satisfied, Venerable Ānanda was
happy with what the Buddha said.
#+end_quote



* Chapter 3
** SUTTA
*** Pāli
#+begin_quote

#+end_quote
*** OWTJ
#+begin_quote

#+end_quote
*** Anigha
#+begin_quote

#+end_quote
** SUTTA
*** Pāli
#+begin_quote

#+end_quote
*** OWTJ
#+begin_quote

#+end_quote
*** Anigha
#+begin_quote

#+end_quote
** SUTTA
*** Pāli
#+begin_quote

#+end_quote
*** OWTJ
#+begin_quote

#+end_quote
*** Anigha
#+begin_quote

#+end_quote
** SUTTA
*** Pāli
#+begin_quote

#+end_quote
*** OWTJ
#+begin_quote

#+end_quote
*** Anigha
#+begin_quote

#+end_quote
** SUTTA
*** Pāli
#+begin_quote

#+end_quote
*** OWTJ
#+begin_quote

#+end_quote
*** Anigha
#+begin_quote

#+end_quote
** SUTTA
*** Pāli
#+begin_quote

#+end_quote
*** OWTJ
#+begin_quote

#+end_quote
*** Anigha
#+begin_quote

#+end_quote
